version: '2'

services:
  simple-tex-service:
    image: ${image}
    # build: .
    ports:
    - 3003
    environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION
    - STS_S3_PUBLIC_URL=https://d2c556so6sqzhx.cloudfront.net/
    - STS_BUCKET_NAME=simple-tex-service
    - STS_HOST=https://tex.beijaflor.io
