version: '2'

services:
  simple-tex-service:
    image: ${image}
    build: .
    ports:
    - 3000
    expose:
    - 3000
    environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION
