name: simple-tex-service
version: '0.4.1.0'
author: Pedro Tacla Yamada
maintainer: yamada@beijaflor.io
license: AllRightsReserved
synopsis: A small service to run tex PDF generation tasks

dependencies:
- Spock
- amazonka
- amazonka-s3
- base >=4.9 && <4.10
- blaze-html
- bytestring
- directory
- lens
- process
- pureMD5
- random
- shakespeare
- temporary >= 1.2.1
- text
- unordered-containers
- uuid
- exceptions
- aeson

executables:
  simple-tex-service:
    main: Main.hs
    source-dirs: src
    ghc-options: -threaded -rtsopts -O2 -with-rtsopts=-N -with-rtsopts=-A128m -with-rtsopts=-qi
