name: simple-tex-service
version: '0.1.0.0'
author: yamadapc
maintainer: tacla.yamada@gmail.com
license: UnspecifiedLicense

dependencies:
- Spock
- amazonka
- amazonka-s3
- base >=4.9 && <4.10
- blaze-html
- bytestring
- directory
- lens
- process
- pureMD5
- random
- shakespeare
- temporary
- text
- unordered-containers
- uuid
- exceptions

executables:
  simple-tex-service:
    main: Main.hs
    source-dirs: src
    ghc-options: -threaded -rtsopts -O2 -with-rtsopts=-N -with-rtsopts=-A128m -with-rtsopts=-qi
