#!/bin/bash -e
name=$1

if [[ $name = "" ]]; then
  echo "Name not specified, using $(basename "$(pwd)")"
  name="$(basename "$(pwd)")"
fi

echo ">>> Building for Linux..."
# stack docker pull
stack build --docker
rm -rf .stack-fpm/linux
mkdir -p .stack-fpm/linux/usr/local
cp -r "$(stack path --docker --local-install-root)"/* ./.stack-fpm/linux/usr/local/
version=$(ggrep -Po "version: '(\K[^']*)" < ./package.yaml)
cd .stack-fpm/linux

echo ">>> Building Linux packages..."
tar -zcvf stack-fpm.tar.gz ./*
fpm -t deb -s tar \
  --deb-pre-depends libgmp-dev \
  --deb-pre-depends texlive-full \
  --deb-pre-depends latex-beamer \
  --deb-pre-depends context \
  --deb-pre-depends make \
  -n "$name" -v "$version" ./stack-fpm.tar.gz

mkdir -p ../../dist
mv ./*.deb ../../dist/
mv ./stack-fpm.tar.gz ../../dist/"$name-$version-linux_amd64.tar.gz"
cd ../..
